//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub use super::wb_comment::Entity as WbComment;
pub use super::wb_feed::Entity as WbFeed;
pub use super::wb_follower::Entity as WbFollower;
pub use super::wb_like::Entity as WbLike;
pub use super::wb_post::Entity as WbPost;
pub use super::wb_user::Entity as WbUser;
pub use super::wb_user_info::Entity as WbUserInfo;

// pub use  xx 表示又引入又导出(重新导出)
// pub use crate::entities::wb_user::Entity as WbUser; 等同 super::wb_user::xx

// src/entities 生成了 prelude.rs文件 为什么 引入了  pub use super::wb_user::Entity as WbUser;
// super指的是谁

// prelude.rs 是 entities 模块下的子模块
// super::wb_user 就表示 entities::wb_user
