//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "wb_post")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub pid: u32,
    pub uid: u32,
    pub content: String,
    pub status: u8,
    pub created_time: u32,
    pub updated_time: u32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
